version: "3.9"
services:
  app:
    build: ./node
    ports:
      - "3000:3000"
    working_dir: "/src"
    volumes:
      -  "./src:/src"
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0.26
    container_name: chat_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"

    volumes:
      - db-data:/var/lib/mysql
      - ./db:/var/src

volumes:
  db-data: